### PR TITLE
Added Singapore Mirror.

### PR DESCRIPTION
**Pull request by xlanor**
Mirror administrator contact if required: contact@jingk.ai

Hosted on a 1000Mbps line. Offers http, https, rsync.

### CODE REVIEW

**Comment by AlpixTM** [comment]
Hey,

thanks for your offer!
I will come back to you within the next 24 hours by mail, I'm on vacation right now!

**Comment by xlanor** [comment]
No problem. Please enjoy your vacation!

**Comment by AlpixTM** [comment]
Status: Mail is ouit

**Comment by xlanor** [comment]
I've replied to your mail with the requested information! @AlpixTM

**Comment by killajoe** [comment]
this is not longer an open task i would bet?
Feel free to reopen if I was wrong with closing.

**Pull request closed without merging**
